import type { Course } from '@lms/core';
import { t } from '../tr';

const ID = 'crs_a1_quotidien';

export const a1QuotidienCourse: Course = {
  id: ID,
  slug: 'a1-quotidien',
  level: 'A1',
  accentFrom: '#7dd3fc',
  accentTo: '#0284c7',
  status: 'published',
  title: t('Ma vie de tous les jours', 'My everyday life', '我的日常生活'),
  subtitle: t('3 leçons · 1 quiz noté', '3 lessons · 1 graded quiz', '3 节课 · 1 次评分测验'),
  description: t(
    'Parler de sa famille, de son logement et de sa journée. Les mots dont on a besoin tous les jours, et les petits mots qui les relient : mon, ma, mes.',
    'Talking about your family, your home and your day. The words you need every day, and the small words that link them: mon, ma, mes.',
    '谈论家人、住处和一天的安排。日常必备的词，以及把它们连起来的小词：mon、ma、mes。',
  ),
  tags: [t('Vocabulaire', 'Vocabulary', '词汇'), t('Débutant', 'Beginner', '初级')],
  modules: [
    {
      id: 'mod_a1qu_1',
      courseId: ID,
      title: t('Autour de moi', 'Around me', '我的周围'),
      summary: t(
        'Les gens, le lieu, le rythme d’une journée.',
        'The people, the place, the rhythm of a day.',
        '身边的人、居住的地方、一天的节奏。',
      ),
      lessons: [
        {
          id: 'les_a1qu_1',
          moduleId: 'mod_a1qu_1',
          kind: 'text',
          durationMin: 10,
          title: t('Ma famille et mes affaires', 'My family and my things', '我的家人和我的东西'),
          summary: t(
            'Dire à qui sont les choses et les gens : mon, ma, mes.',
            'Saying who things and people belong to: mon, ma, mes.',
            '说明人和物属于谁：mon、ma、mes。',
          ),
          blocks: [
            {
              type: 'paragraph',
              emoji: '👨‍👩‍👧',
              text: t(
                'Pour parler des gens autour de vous, il vous faut deux choses. D’abord les mots de la famille. Ensuite le petit mot qui va devant : **mon**, **ma** ou **mes**. Il correspond à « my » en anglais, mais il change de forme.',
                'To talk about the people around you, you need two things. First the family words. Then the little word that goes in front: **mon**, **ma** or **mes**. It works like “my” in English, except that it changes shape.',
                '要谈论身边的人，需要两样东西。首先是家庭称谓。其次是放在前面的小词：**mon**、**ma** 或 **mes**。它相当于英语的 “my”，只是形式会变。',
              ),
            },
            {
              type: 'callout',
              tone: 'warning',
              emoji: '🔑',
              title: t(
                'Le point clé : c’est l’objet qui décide, pas vous',
                'The key point: the object decides, not you',
                '关键：由所属之物决定，而非由您决定',
              ),
              text: t(
                'En anglais, on dit « his sister » ou « her sister » selon la personne qui parle. En français, non : on dit **sa** sœur dans les deux cas, parce que « sœur » est un mot féminin. C’est le mot qui suit qui commande.',
                'In English you say “his sister” or “her sister” depending on the owner. Not in French: you say **sa** sœur in both cases, because “sœur” is a feminine word. The word that follows is what decides.',
                '英语中根据所有者说 “his sister” 或 “her sister”。法语不然：两种情况都说 **sa** sœur，因为 “sœur” 是阴性词。决定形式的是后面那个词。',
              ),
            },
            {
              type: 'interactive',
              emoji: '🎛️',
              title: t('Mon, ma, mes : le sélecteur', 'Mon, ma, mes: the picker', 'Mon、ma、mes 选择器'),
              hint: t(
                'Choisissez qui possède, puis ce qu’il possède, {prenom}.',
                'Pick who owns it, then what they own, {prenom}.',
                '{prenom}，先选择所有者，再选择所属之物。',
              ),
              widget: {
                kind: 'matrix',
                rowsLabel: t('Qui possède', 'Who owns it', '所有者'),
                columnsLabel: t('Ce qui est possédé', 'What is owned', '所属之物'),
                rows: [
                  { id: 'je', label: t('moi', 'me', '我') },
                  { id: 'tu', label: t('toi', 'you', '你') },
                  { id: 'il', label: t('lui ou elle', 'him or her', '他或她') },
                  { id: 'nous', label: t('nous', 'us', '我们') },
                ],
                columns: [
                  { id: 'm', label: t('un mot masculin', 'a masculine word', '阳性词') },
                  { id: 'f', label: t('un mot féminin', 'a feminine word', '阴性词') },
                  { id: 'p', label: t('plusieurs choses', 'several things', '多样东西') },
                ],
                cells: [
                  { row: 'je', column: 'm', answer: 'mon', example: 'mon frère, mon appartement', gloss: t('Devant un mot masculin, on dit « mon ».', 'Before a masculine word, you say “mon”.', '阳性词前用 “mon”。') },
                  { row: 'je', column: 'f', answer: 'ma', example: 'ma sœur, ma chambre', gloss: t('Devant un mot féminin, « ma ». Mais devant une voyelle, on repasse à « mon » : mon amie.', 'Before a feminine word, “ma”. But before a vowel you go back to “mon”: mon amie.', '阴性词前用 “ma”。但元音前又改回 “mon”：mon amie。') },
                  { row: 'je', column: 'p', answer: 'mes', example: 'mes parents, mes clés', gloss: t('Au pluriel, une seule forme pour les deux genres : « mes ».', 'In the plural, one form for both genders: “mes”.', '复数时两种性别只有一个形式：“mes”。') },
                  { row: 'tu', column: 'm', answer: 'ton', example: 'ton père, ton livre', gloss: t('Même logique que « mon », avec « ton ».', 'Same logic as “mon”, with “ton”.', '与 “mon” 逻辑相同，换成 “ton”。') },
                  { row: 'tu', column: 'f', answer: 'ta', example: 'ta mère, ta maison', gloss: t('Et « ton amie » devant une voyelle, jamais « ta amie ».', 'And “ton amie” before a vowel, never “ta amie”.', '元音前说 “ton amie”，绝不说 “ta amie”。') },
                  { row: 'tu', column: 'p', answer: 'tes', example: 'tes amis, tes affaires', gloss: t('Une seule forme au pluriel, comme partout.', 'One form in the plural, as everywhere.', '与各处相同，复数只有一个形式。') },
                  { row: 'il', column: 'm', answer: 'son', example: 'son frère', gloss: t('« Son frère » peut être celui d’un homme ou d’une femme : le français ne le dit pas.', '“Son frère” can be a man’s or a woman’s: French does not say which.', '“Son frère” 可能是男性的也可能是女性的：法语不作区分。') },
                  { row: 'il', column: 'f', answer: 'sa', example: 'sa sœur', gloss: t('Là encore, « sa sœur » ne dit rien du propriétaire. C’est le mot « sœur » qui impose « sa ».', 'Again, “sa sœur” says nothing about the owner. It is the word “sœur” that imposes “sa”.', '同样，“sa sœur” 不透露所有者信息。是 “sœur” 一词决定用 “sa”。') },
                  { row: 'il', column: 'p', answer: 'ses', example: 'ses enfants', gloss: t('« Ses enfants » : les siens à lui, ou à elle. Le contexte tranche.', '“Ses enfants”: his or hers. Context decides.', '“Ses enfants”：他的或她的，由上下文判断。') },
                  { row: 'nous', column: 'm', answer: 'notre', example: 'notre fils', gloss: t('À partir de « nous », plus de distinction de genre : « notre » sert aux deux.', 'From “nous” on, no gender distinction: “notre” serves both.', '从 “nous” 开始不再区分性别：“notre” 通用。') },
                  { row: 'nous', column: 'f', answer: 'notre', example: 'notre fille', gloss: t('Même mot qu’au masculin. C’est plus simple à partir d’ici.', 'The same word as the masculine. It gets simpler from here.', '与阳性同形。从这里开始更简单了。') },
                  { row: 'nous', column: 'p', answer: 'nos', example: 'nos enfants', gloss: t('Au pluriel, « nos ». Une seule chose à retenir.', 'In the plural, “nos”. Just one thing to remember.', '复数用 “nos”。只需记住一点。') },
                ],
              },
            },
            {
              type: 'keyvalues',
              emoji: '🗂️',
              title: t('Les mots de la famille', 'Family words', '家庭称谓'),
              entries: [
                { label: t('Les parents', 'Parents', '父母'), value: t('le père, la mère, les parents. « Les parents » veut dire le père et la mère, pas « les proches ».', 'le père, la mère, les parents. “Les parents” means the father and the mother, not “relatives”.', 'le père、la mère、les parents。“Les parents” 指父母双亲，而非“亲戚”。') },
                { label: t('Les enfants', 'Children', '子女'), value: t('le fils, la fille, les enfants. Attention : « fille » veut dire à la fois « daughter » et « girl ».', 'le fils, la fille, les enfants. Note: “fille” means both “daughter” and “girl”.', 'le fils、la fille、les enfants。注意：“fille” 既指“女儿”也指“女孩”。') },
                { label: t('Les frères et sœurs', 'Siblings', '兄弟姐妹'), value: t('le frère, la sœur. Pour dire « siblings », le français dit « les frères et sœurs ».', 'le frère, la sœur. For “siblings”, French says “les frères et sœurs”.', 'le frère、la sœur。表示“兄弟姐妹”，法语说 “les frères et sœurs”。') },
                { label: t('Les grands-parents', 'Grandparents', '祖父母'), value: t('le grand-père, la grand-mère. Et les petits-enfants, dans l’autre sens.', 'le grand-père, la grand-mère. And les petits-enfants, the other way round.', 'le grand-père、la grand-mère。反过来则是 les petits-enfants。') },
                { label: t('Le couple', 'The couple', '伴侣'), value: t('le mari, la femme. « Ma femme » veut dire « my wife » ; pour « a woman », on dit « une femme ».', 'le mari, la femme. “Ma femme” means “my wife”; for “a woman”, you say “une femme”.', 'le mari、la femme。“Ma femme” 意为“我妻子”；表示“一位女性”则说 “une femme”。') },
              ],
            },
            {
              type: 'interactive',
              emoji: '🧩',
              title: t('Complétez les phrases', 'Complete the sentences', '补全句子'),
              hint: t(
                'Une seule forme est juste à chaque fois.',
                'Only one form is right each time.',
                '每次只有一个形式正确。',
              ),
              widget: {
                kind: 'fill',
                prompt: t('Choisissez la bonne forme :', 'Pick the right form:', '选择正确的形式：'),
                items: [
                  {
                    id: 'f1',
                    before: 'Voici ',
                    after: ' sœur, elle s’appelle Léa.',
                    options: ['mon', 'ma', 'mes'],
                    answer: 'ma',
                    why: t('« Sœur » est féminin et commence par une consonne : « ma ».', '“Sœur” is feminine and starts with a consonant: “ma”.', '“Sœur” 是阴性且以辅音开头：用 “ma”。'),
                  },
                  {
                    id: 'f2',
                    before: 'Je vous présente ',
                    after: ' amie Claire.',
                    options: ['mon', 'ma', 'mes'],
                    answer: 'mon',
                    why: t('« Amie » est féminin, mais commence par une voyelle : on dit « mon » pour éviter deux voyelles qui se suivent.', '“Amie” is feminine, but starts with a vowel: you say “mon” to avoid two vowels in a row.', '“Amie” 是阴性，但以元音开头：用 “mon” 以避免两个元音相连。'),
                  },
                  {
                    id: 'f3',
                    before: 'Elle habite avec ',
                    after: ' parents.',
                    options: ['son', 'sa', 'ses'],
                    answer: 'ses',
                    why: t('« Parents » est pluriel : une seule forme possible, « ses ».', '“Parents” is plural: only one possible form, “ses”.', '“Parents” 是复数：只有一个可能的形式 “ses”。'),
                  },
                  {
                    id: 'f4',
                    before: 'Paul cherche ',
                    after: ' clés depuis ce matin.',
                    options: ['son', 'sa', 'ses'],
                    answer: 'ses',
                    why: t('« Clés » est au pluriel, donc « ses », même si Paul est un homme.', '“Clés” is plural, so “ses”, even though Paul is a man.', '“Clés” 是复数，所以用 “ses”，尽管 Paul 是男性。'),
                  },
                ],
              },
            },
          ],
        },
        {
          id: 'les_a1qu_2',
          moduleId: 'mod_a1qu_1',
          kind: 'text',
          durationMin: 10,
          title: t('Où j’habite', 'Where I live', '我住在哪里'),
          summary: t(
            'Décrire son logement et dire où se trouvent les choses.',
            'Describing your home and saying where things are.',
            '描述住处，说明东西在哪里。',
          ),
          blocks: [
            {
              type: 'paragraph',
              emoji: '🏠',
              text: t(
                'On vous demandera souvent où vous habitez. La réponse tient en trois informations : le type de logement, la ville, et une pièce ou deux si on vous en demande plus.',
                'People will often ask where you live. The answer comes down to three things: the type of home, the city, and a room or two if they ask for more.',
                '别人常会问您住在哪里。回答包含三项信息：住所类型、城市，若对方还想知道更多，再说一两个房间。',
              ),
            },
            {
              type: 'examples',
              emoji: '💬',
              title: t('Trois phrases à connaître', 'Three sentences to know', '需掌握的三句话'),
              items: [
                { fr: 'J’habite dans un appartement, à Lyon.', gloss: t('« Dans » pour le logement, « à » pour la ville.', '“Dans” for the home, “à” for the city.', '住所前用 “dans”，城市前用 “à”。') },
                { fr: 'C’est un deux-pièces, au troisième étage.', gloss: t('En France, on compte les pièces sans la cuisine ni la salle de bains.', 'In France you count the rooms without the kitchen or the bathroom.', '在法国，房间数不含厨房和浴室。') },
                { fr: 'J’habite en colocation avec deux amis.', gloss: t('Très courant chez les étudiants et les jeunes actifs.', 'Very common among students and young professionals.', '在学生和年轻职场人中非常普遍。') },
                { fr: 'J’habite à un appartement.', gloss: t('On habite **dans** un logement, jamais « à ».', 'You live **dans** a home, never “à”.', '住在某处用 **dans**，绝不用 “à”。'), incorrect: true },
              ],
            },
            {
              type: 'interactive',
              emoji: '🏡',
              title: t('Les pièces de la maison', 'The rooms of a home', '住所的房间'),
              hint: t(
                'Cliquez une pièce du plan pour voir son nom et ce qu’on y fait.',
                'Click a room on the plan to see its name and what happens there.',
                '点击平面图上的房间，查看名称及用途。',
              ),
              widget: {
                kind: 'layout',
                ratio: 1.35,
                zones: [
                  {
                    id: 'entree',
                    label: t('L’entrée', 'The hallway', '门厅'),
                    x: 4, y: 62, w: 22, h: 32,
                    sample: 'l’entrée',
                    detail: t('On y laisse ses chaussures et son manteau. « Entrez ! » est ce qu’on dit pour inviter quelqu’un à y venir.', 'You leave your shoes and coat there. “Entrez !” is what you say to invite someone in.', '在这里脱鞋挂外套。请人进门时说 “Entrez !”。'),
                  },
                  {
                    id: 'salon',
                    label: t('Le salon', 'The living room', '客厅'),
                    x: 28, y: 44, w: 40, h: 50,
                    sample: 'le salon',
                    detail: t('La pièce principale, où l’on reçoit. On dit aussi « le séjour ». C’est là qu’on regarde la télévision.', 'The main room, where you receive guests. Also called “le séjour”. This is where you watch television.', '主要房间，用于待客，也叫 “le séjour”。在这里看电视。'),
                  },
                  {
                    id: 'cuisine',
                    label: t('La cuisine', 'The kitchen', '厨房'),
                    x: 70, y: 44, w: 26, h: 50,
                    sample: 'la cuisine',
                    detail: t('« Cuisine » veut dire à la fois la pièce et l’art de cuisiner : « la cuisine française » est célèbre.', '“Cuisine” means both the room and cooking itself: “la cuisine française” is famous.', '“Cuisine” 既指厨房也指烹饪：“la cuisine française” 享有盛名。'),
                  },
                  {
                    id: 'chambre',
                    label: t('La chambre', 'The bedroom', '卧室'),
                    x: 4, y: 6, w: 44, h: 34,
                    sample: 'la chambre',
                    detail: t('Attention au faux ami : « chambre » n’est pas « chamber », c’est la pièce où l’on dort.', 'Watch the false friend: “chambre” is not “chamber”, it is the room where you sleep.', '注意假朋友：“chambre” 不是 “chamber”，而是睡觉的房间。'),
                  },
                  {
                    id: 'sdb',
                    label: t('La salle de bains', 'The bathroom', '浴室'),
                    x: 50, y: 6, w: 26, h: 34,
                    sample: 'la salle de bains',
                    detail: t('Avec un « s » à « bains », toujours. La pièce avec les toilettes est souvent séparée : « les WC ».', 'Always with an “s” on “bains”. The room with the toilet is often separate: “les WC”.', '“bains” 后面永远有 “s”。厕所通常是单独的一间：“les WC”。'),
                  },
                  {
                    id: 'balcon',
                    label: t('Le balcon', 'The balcony', '阳台'),
                    x: 78, y: 6, w: 18, h: 34,
                    sample: 'le balcon',
                    detail: t('Un argument de poids dans une annonce immobilière française, surtout dans le Sud.', 'A strong selling point in a French property ad, especially in the south.', '在法国房产广告中是重要卖点，南方尤其如此。'),
                  },
                ],
              },
            },
            {
              type: 'callout',
              tone: 'info',
              emoji: '📐',
              title: t('Les étages ne se comptent pas pareil', 'Floors are not counted the same way', '楼层的数法不同'),
              text: t(
                'Le rez-de-chaussée est au niveau de la rue. Le « premier étage » est donc le deuxième niveau — ce que l’anglais américain appelle « second floor ». Un ascenseur français affiche donc **0** pour la rue.',
                'The rez-de-chaussée is at street level. So the “premier étage” is the second level — what American English calls the “second floor”. A French lift therefore shows **0** for the street.',
                'Rez-de-chaussée 是临街的一层。因此 “premier étage” 是第二层——即美式英语所说的 “second floor”。法国电梯用 **0** 表示街面层。',
              ),
            },
          ],
        },
        {
          id: 'les_a1qu_3',
          moduleId: 'mod_a1qu_1',
          kind: 'text',
          durationMin: 10,
          title: t('Ma journée', 'My day', '我的一天'),
          summary: t(
            'Raconter sa journée avec les verbes qui reviennent le plus.',
            'Telling your day with the verbs that come up most.',
            '用最常用的动词讲述一天。',
          ),
          blocks: [
            {
              type: 'paragraph',
              emoji: '⏰',
              text: t(
                'Une journée se raconte avec une dizaine de verbes, pas davantage. Beaucoup sont des verbes pronominaux : ils portent un petit « se » qui devient « me » quand on parle de soi.',
                'A day is told with about ten verbs, no more. Many are reflexive: they carry a small “se” that becomes “me” when you talk about yourself.',
                '讲述一天大约只需十来个动词。其中许多是自反动词：带有一个小小的 “se”，谈自己时变成 “me”。',
              ),
            },
            {
              type: 'callout',
              tone: 'info',
              emoji: '🔁',
              title: t('Le petit « se » expliqué simplement', 'The little “se”, explained simply', '简单解释这个小小的 “se”'),
              text: t(
                'Il indique que l’action revient sur celui qui la fait. « Je lave la voiture » : je lave autre chose. « Je **me** lave » : je lave moi-même. Le « se » de l’infinitif devient **me**, **te**, **se**, **nous**, **vous**.',
                'It shows the action comes back onto the person doing it. “Je lave la voiture”: I wash something else. “Je **me** lave”: I wash myself. The “se” of the infinitive becomes **me**, **te**, **se**, **nous**, **vous**.',
                '它表示动作回到施动者自身。“Je lave la voiture”：我洗别的东西。“Je **me** lave”：我洗自己。不定式中的 “se” 变为 **me**、**te**、**se**、**nous**、**vous**。',
              ),
            },
            {
              type: 'interactive',
              emoji: '🌅',
              title: t('Remettez la journée dans l’ordre', 'Put the day back in order', '把一天的顺序排好'),
              hint: t(
                'Cliquez les actions dans l’ordre où on les fait.',
                'Click the actions in the order you do them.',
                '按实际发生的顺序点击各项动作。',
              ),
              widget: {
                kind: 'order',
                prompt: t(
                  'Une journée ordinaire, du réveil au coucher :',
                  'An ordinary day, from waking up to going to bed:',
                  '普通的一天，从起床到睡觉：',
                ),
                items: [
                  { id: 'o1', text: t('Je me réveille à sept heures.', 'Je me réveille à sept heures.', 'Je me réveille à sept heures.') },
                  { id: 'o2', text: t('Je me lève et je prends une douche.', 'Je me lève et je prends une douche.', 'Je me lève et je prends une douche.') },
                  { id: 'o3', text: t('Je prends mon petit-déjeuner.', 'Je prends mon petit-déjeuner.', 'Je prends mon petit-déjeuner.') },
                  { id: 'o4', text: t('Je vais au travail.', 'Je vais au travail.', 'Je vais au travail.') },
                  { id: 'o5', text: t('Je déjeune avec des collègues.', 'Je déjeune avec des collègues.', 'Je déjeune avec des collègues.') },
                  { id: 'o6', text: t('Je rentre chez moi.', 'Je rentre chez moi.', 'Je rentre chez moi.') },
                  { id: 'o7', text: t('Je me couche vers onze heures.', 'Je me couche vers onze heures.', 'Je me couche vers onze heures.') },
                ],
                successNote: t(
                  'Remarquez « chez moi » : le français n’a pas de mot pour « home », il dit « chez » suivi de la personne.',
                  'Notice “chez moi”: French has no word for “home”, it says “chez” followed by the person.',
                  '注意 “chez moi”：法语没有对应 “home” 的词，而是用 “chez” 加上人称。',
                ),
              },
            },
            {
              type: 'conjugation',
              emoji: '🔄',
              title: t('Se lever au présent', 'Se lever in the present', 'Se lever 的现在时'),
              note: t(
                'Le « se » se place entre le sujet et le verbe. Il ne disparaît jamais : sans lui, la phrase change de sens.',
                'The “se” sits between the subject and the verb. It never disappears: without it, the sentence changes meaning.',
                '“se” 位于主语和动词之间。它绝不会消失：没有它，句意就变了。',
              ),
              columns: [t('se lever', 'se lever', 'se lever')],
              rows: [
                { pronoun: 'je', forms: ['me lève'] },
                { pronoun: 'tu', forms: ['te lèves'] },
                { pronoun: 'il / elle / on', forms: ['se lève'] },
                { pronoun: 'nous', forms: ['nous levons'] },
                { pronoun: 'vous', forms: ['vous levez'] },
                { pronoun: 'ils / elles', forms: ['se lèvent'] },
              ],
            },
            {
              type: 'interactive',
              emoji: '🔗',
              title: t('Reliez le verbe à son sens', 'Match the verb to its meaning', '把动词与意思配对'),
              hint: t(
                'Choisissez une expression, puis ce qu’elle veut dire.',
                'Pick an expression, then what it means.',
                '先选一个表达，再选它的意思。',
              ),
              widget: {
                kind: 'pairs',
                prompt: t('Les gestes du quotidien :', 'Everyday actions:', '日常动作：'),
                pairs: [
                  { id: 'p1', left: 'se réveiller', right: t('ouvrir les yeux, sans forcément sortir du lit', 'to open your eyes, without necessarily getting up', '睁开眼睛，不一定起身') },
                  { id: 'p2', left: 'se lever', right: t('sortir du lit et se mettre debout', 'to get out of bed and stand up', '下床站起来') },
                  { id: 'p3', left: 'prendre une douche', right: t('se laver sous l’eau, debout', 'to wash under running water, standing', '站着淋浴') },
                  { id: 'p4', left: 's’habiller', right: t('mettre ses vêtements', 'to put your clothes on', '穿衣服') },
                  { id: 'p5', left: 'rentrer', right: t('revenir chez soi, en fin de journée', 'to come back home at the end of the day', '一天结束时回到家') },
                  { id: 'p6', left: 'se coucher', right: t('aller au lit pour dormir', 'to go to bed to sleep', '上床睡觉') },
                ],
              },
            },
          ],
        },
      ],
    },
    {
      id: 'mod_a1qu_q',
      courseId: ID,
      title: t('Évaluation', 'Assessment', '测评'),
      summary: t('Six questions sur la famille, le logement et la journée.', 'Six questions on family, home and daily routine.', '六道题，考查家庭、住处与日常作息。'),
      lessons: [
        {
          id: 'les_a1qu_q',
          moduleId: 'mod_a1qu_q',
          kind: 'quiz',
          durationMin: 6,
          quizId: 'qz_a1_quotidien',
          title: t('Quiz — Ma vie de tous les jours', 'Quiz — My everyday life', '测验 — 我的日常生活'),
          summary: t('6 questions sur le vocabulaire du quotidien.', '6 questions on everyday vocabulary.', '6 道题，考查日常词汇。'),
        },
      ],
    },
  ],
};
